/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initial Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hclscope.hclScope.InitialTransition#getInitialto <em>Initialto</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.InitialTransition#getInitialState <em>Initial State</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getInitialTransition()
 * @model
 * @generated
 */
public interface InitialTransition extends Transitions
{
  /**
	 * Returns the value of the '<em><b>Initialto</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Initialto</em>' reference.
	 * @see #setInitialto(Vertex)
	 * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getInitialTransition_Initialto()
	 * @model
	 * @generated
	 */
  Vertex getInitialto();

  /**
	 * Sets the value of the '{@link org.xtext.example.hclscope.hclScope.InitialTransition#getInitialto <em>Initialto</em>}' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Initialto</em>' reference.
	 * @see #getInitialto()
	 * @generated
	 */
  void setInitialto(Vertex value);

		/**
	 * Returns the value of the '<em><b>Initial State</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Initial State</em>' reference.
	 * @see #setInitialState(InitialState)
	 * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getInitialTransition_InitialState()
	 * @model
	 * @generated
	 */
	InitialState getInitialState();

		/**
	 * Sets the value of the '{@link org.xtext.example.hclscope.hclScope.InitialTransition#getInitialState <em>Initial State</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Initial State</em>' reference.
	 * @see #getInitialState()
	 * @generated
	 */
	void setInitialState(InitialState value);

} // InitialTransition
