/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.hclscope.hclScope.DeepHistory;
import org.xtext.example.hclscope.hclScope.HclScopePackage;
import org.xtext.example.hclscope.hclScope.HistoryTransition;
import org.xtext.example.hclscope.hclScope.Vertex;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>History Transition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.HistoryTransitionImpl#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.HistoryTransitionImpl#getHistory <em>History</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HistoryTransitionImpl extends TransitionsImpl implements HistoryTransition
{
  /**
	 * The cached value of the '{@link #getFrom() <em>From</em>}' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getFrom()
	 * @generated
	 * @ordered
	 */
  protected Vertex from;

  /**
	 * The cached value of the '{@link #getHistory() <em>History</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getHistory()
	 * @generated
	 * @ordered
	 */
	protected DeepHistory history;

		/**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected HistoryTransitionImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return HclScopePackage.Literals.HISTORY_TRANSITION;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Vertex getFrom()
  {
		if (from != null && from.eIsProxy()) {
			InternalEObject oldFrom = (InternalEObject)from;
			from = (Vertex)eResolveProxy(oldFrom);
			if (from != oldFrom) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, HclScopePackage.HISTORY_TRANSITION__FROM, oldFrom, from));
			}
		}
		return from;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Vertex basicGetFrom()
  {
		return from;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void setFrom(Vertex newFrom)
  {
		Vertex oldFrom = from;
		from = newFrom;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HclScopePackage.HISTORY_TRANSITION__FROM, oldFrom, from));
	}

  /**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public DeepHistory getHistory() {
		if (history != null && history.eIsProxy()) {
			InternalEObject oldHistory = (InternalEObject)history;
			history = (DeepHistory)eResolveProxy(oldHistory);
			if (history != oldHistory) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, HclScopePackage.HISTORY_TRANSITION__HISTORY, oldHistory, history));
			}
		}
		return history;
	}

		/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DeepHistory basicGetHistory() {
		return history;
	}

		/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setHistory(DeepHistory newHistory) {
		DeepHistory oldHistory = history;
		history = newHistory;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HclScopePackage.HISTORY_TRANSITION__HISTORY, oldHistory, history));
	}

		/**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
		switch (featureID) {
			case HclScopePackage.HISTORY_TRANSITION__FROM:
				if (resolve) return getFrom();
				return basicGetFrom();
			case HclScopePackage.HISTORY_TRANSITION__HISTORY:
				if (resolve) return getHistory();
				return basicGetHistory();
		}
		return super.eGet(featureID, resolve, coreType);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eSet(int featureID, Object newValue)
  {
		switch (featureID) {
			case HclScopePackage.HISTORY_TRANSITION__FROM:
				setFrom((Vertex)newValue);
				return;
			case HclScopePackage.HISTORY_TRANSITION__HISTORY:
				setHistory((DeepHistory)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eUnset(int featureID)
  {
		switch (featureID) {
			case HclScopePackage.HISTORY_TRANSITION__FROM:
				setFrom((Vertex)null);
				return;
			case HclScopePackage.HISTORY_TRANSITION__HISTORY:
				setHistory((DeepHistory)null);
				return;
		}
		super.eUnset(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public boolean eIsSet(int featureID)
  {
		switch (featureID) {
			case HclScopePackage.HISTORY_TRANSITION__FROM:
				return from != null;
			case HclScopePackage.HISTORY_TRANSITION__HISTORY:
				return history != null;
		}
		return super.eIsSet(featureID);
	}

} //HistoryTransitionImpl
