/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.hclscope.hclScope.HclScopePackage;
import org.xtext.example.hclscope.hclScope.InitialState;
import org.xtext.example.hclscope.hclScope.InitialTransition;
import org.xtext.example.hclscope.hclScope.Vertex;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Initial Transition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.InitialTransitionImpl#getInitialto <em>Initialto</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.InitialTransitionImpl#getInitialState <em>Initial State</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InitialTransitionImpl extends TransitionsImpl implements InitialTransition
{
  /**
	 * The cached value of the '{@link #getInitialto() <em>Initialto</em>}' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getInitialto()
	 * @generated
	 * @ordered
	 */
  protected Vertex initialto;

		/**
	 * The cached value of the '{@link #getInitialState() <em>Initial State</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getInitialState()
	 * @generated
	 * @ordered
	 */
	protected InitialState initialState;

		/**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected InitialTransitionImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return HclScopePackage.Literals.INITIAL_TRANSITION;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Vertex getInitialto()
  {
		if (initialto != null && initialto.eIsProxy()) {
			InternalEObject oldInitialto = (InternalEObject)initialto;
			initialto = (Vertex)eResolveProxy(oldInitialto);
			if (initialto != oldInitialto) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, HclScopePackage.INITIAL_TRANSITION__INITIALTO, oldInitialto, initialto));
			}
		}
		return initialto;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Vertex basicGetInitialto()
  {
		return initialto;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void setInitialto(Vertex newInitialto)
  {
		Vertex oldInitialto = initialto;
		initialto = newInitialto;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HclScopePackage.INITIAL_TRANSITION__INITIALTO, oldInitialto, initialto));
	}

  /**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public InitialState getInitialState() {
		if (initialState != null && initialState.eIsProxy()) {
			InternalEObject oldInitialState = (InternalEObject)initialState;
			initialState = (InitialState)eResolveProxy(oldInitialState);
			if (initialState != oldInitialState) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, HclScopePackage.INITIAL_TRANSITION__INITIAL_STATE, oldInitialState, initialState));
			}
		}
		return initialState;
	}

		/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public InitialState basicGetInitialState() {
		return initialState;
	}

		/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setInitialState(InitialState newInitialState) {
		InitialState oldInitialState = initialState;
		initialState = newInitialState;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HclScopePackage.INITIAL_TRANSITION__INITIAL_STATE, oldInitialState, initialState));
	}

		/**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
		switch (featureID) {
			case HclScopePackage.INITIAL_TRANSITION__INITIALTO:
				if (resolve) return getInitialto();
				return basicGetInitialto();
			case HclScopePackage.INITIAL_TRANSITION__INITIAL_STATE:
				if (resolve) return getInitialState();
				return basicGetInitialState();
		}
		return super.eGet(featureID, resolve, coreType);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eSet(int featureID, Object newValue)
  {
		switch (featureID) {
			case HclScopePackage.INITIAL_TRANSITION__INITIALTO:
				setInitialto((Vertex)newValue);
				return;
			case HclScopePackage.INITIAL_TRANSITION__INITIAL_STATE:
				setInitialState((InitialState)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eUnset(int featureID)
  {
		switch (featureID) {
			case HclScopePackage.INITIAL_TRANSITION__INITIALTO:
				setInitialto((Vertex)null);
				return;
			case HclScopePackage.INITIAL_TRANSITION__INITIAL_STATE:
				setInitialState((InitialState)null);
				return;
		}
		super.eUnset(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public boolean eIsSet(int featureID)
  {
		switch (featureID) {
			case HclScopePackage.INITIAL_TRANSITION__INITIALTO:
				return initialto != null;
			case HclScopePackage.INITIAL_TRANSITION__INITIAL_STATE:
				return initialState != null;
		}
		return super.eIsSet(featureID);
	}

} //InitialTransitionImpl
